# Todos

## General

- bale ta ballast trips apo ships tensor pisw sto ships df ❌
- ananewne ka8w fora ta contracts_df kai ships_df me oti allagh ginetai stous contracts_tensor kai ships_tensor


## Step

### Allakse to state otan allazei h mera ❌

afou looparw se ola ta available ships shmainei oti h mera allazei

   #### - diamorfwse katallhla to ships log ❌
   
          * to ships log prepei na exei values >= 0 ❌
          * apo mh mhdenika ships log values afairese 1 epeidh perase mia mera ❌
          * an prokypsoun ships_log[ship] = 0 tote kane to `ship_availability` autou tou ship 1 ❌
          * osa ships einai available (exoun ships_log[ship] == 0) bainoun se lista `available_ships` pou 8a thn allazeis ka8e mera. ❌
           

   #### -  kane generate 4 nea contracts ❌

### Pws ypologizw to `reward` apo to action  ✅
    

   #### - Value of contract ✅
   #### - CII ✅
   #### - Lateness ✅
   #### - Ftiakse sugentrwtiko `calculate_reward(selected_ship_idx,selected_contract,selected_speed)` function ✅

### Pws na kanw swsta update to `state`  ✅
  

      
   #### - contract tensor ✅
   #### - ship tensor ✅
   #### - contract mask ✅
   #### - ship mask ✅
   #### - ship_log ✅
        

## Train 

ti einai ta `advantages`, `returns` kai giati xrhsimopoioyntai:
        
- ❌ sthn baseline_net.update(observations, returns) gia to update to baselineNet
- ❌ sthn PolicyGradient.update_policy(observations, actions, advantages)gia to update ths policygradient 

# Code

In [1]:
# autoreloading modules that i change in vscode
%load_ext autoreload
%autoreload 2

In [2]:
import gym
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

In [3]:
# load data
data_dict = {
    "fleet_path": "data/fleet_small.csv",
    "ports_path": "data/ports_10.csv",
    "dm_path": "data/distance_matrix.csv",
}


ports_df = pd.read_csv(data_dict["ports_path"])
fleet_df = pd.read_csv(data_dict["fleet_path"])
distance_matrix = pd.read_csv(data_dict["dm_path"])

In [4]:
from env.env import CarbonEnv
from models.models import BaselineNet, PolicyNet, CarbonModel
from utils.utils import map_action

In [ ]:
# run this cell when needing to reload the classes CarbonEnv, BaselineNet, PolicyNet

del sys.modules['models.models']
del sys.modules['env.env']

from env.env import CarbonEnv
from models.models import BaselineNet, PolicyNet, CarbonModel
from utils.utils import map_action

In [5]:
envo = CarbonEnv()

2021-11-15 13:40:30.783639: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-15 13:40:30.784549: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [ ]:
envo.contracts_df

In [ ]:
envo.ships

In [ ]:
# something
s = np.array([[0], [0], [0], [1]])


k = np.where(s==0,3*[False],3*[True])

k

k.ravel()

st = tf.convert_to_tensor(s)
st

bm = tf.equal(st,0)


skou = tf.where(bm,tf.repeat(tf.constant(False),3),tf.repeat(tf.constant(True),3))
skou

skou = tf.reshape(skou,[-1])
skou

skou = tf.expand_dims(skou,axis=1)
skou

bol = tf.constant(False,shape=(1,1))

tf.concat((skou,bol),axis=0)

In [6]:
initial_state = envo.state

In [ ]:
envo.ships_log

In [ ]:
initial_state['ships_state'][:,-4:].numpy()

In [ ]:
baseline_net = BaselineNet(embedding_size=envo.embedding_size,output_size=1)

In [7]:
policy_net = PolicyNet(embedding_size=envo.embedding_size,output_size=envo.action_space_dim[0])

In [9]:
logits, distr = policy_net.action_distribution(initial_state)

In [11]:
action = policy_net.sample_action(initial_state)

In [12]:
action

5

In [ ]:
# estw oti dialegw to ship 1 mesa sth loopa twn ships
# h loopa twn ships einai prin to sample_action

ship_number = 1
ship_idx = ship_number - 1

In [ ]:
envo.ships

In [ ]:
envo.contracts_df

In [31]:
x = envo.step(action=0,ship_number=1)

The contract selected is contract_0 and the speed selected for ship 1 is 10 knots
Bhka sto if, phra contract ! :D
To reward sthn arxh einai 0
To start port tou contract_0 einai to 5.0
To end port tou contract_0 einai to 10.0
H apostash metaksy twn dyo autwn port einai 425.0 nm
To ballast_idx pou epileksame einai to ballast_0 pou einai to feature 7 tou ship_tensor
To ploio 1 brisketai sto current port 10.0
To ballast distance metaksy current port 10.0 kai start port 5.0 prokyptei 83.0 nm
To synoliko distance einai 425.0 nm + 83.0 nm = 508.0 nm
To ship 1 8a ftasei 3.0 meres nwritera
to distance sailed einai 508.0
To dwt einai 50000
O c3 speed factor einai 0.00085034
O c2 speed factor einai 0.15646258
Ta co2 emissions einai 16.496598
O ari8mhths einai 16496597.999999998
O paronomasths einai 25400000.0
The total reward is made up by the contract value 6.0
The delay reward is 3.0
The cii reward is 4.086238861083984
to shape tou contracts_mask einai (4,)
tf.Tensor(1.2989447, shape=(), dtype=

In [32]:
envo.ships_log

{1: -3.0, 2: 0, 3: 0, 4: 0}

In [34]:
x = envo.ships_log[1]

In [43]:
x = -1

In [37]:
 -x if x < 0 else x

3.0

In [44]:
days_of_unaivailability =  -x if x < 0 else x
days_of_unaivailability

1

In [50]:
my_dict = {1:-1, 2:4, 3:0, 4:-5}

In [71]:
available_ships = []
for k,v in my_dict.items():
    my_dict[k] -= 1
    if my_dict[k] < 0:
        my_dict[k] = 0
        available_ships.append(k)
        
my_dict

{1: 0, 2: 2, 3: 0, 4: 0}

In [49]:
my_dict

{1: 0, 2: 3, 3: 0, 4: 0}

In [52]:
available_ships

[1, 3, 4]

In [72]:
available_ships_idx = [x - 1 for x in available_ships]
available_ships_idx

[0, 2, 3]

In [82]:
ships_tensor = envo.ships_tensor
ships_tensor

<tf.Tensor: shape=(4, 11), dtype=float32, numpy=
array([[1.0000000e+00, 5.0000000e+04, 5.3851833e+00, 1.2989447e+00,
        1.0000000e+01, 1.0000000e+01, 0.0000000e+00, 8.3000000e+01,
        3.4200000e+02, 1.1400000e+03, 1.2560000e+03],
       [2.0000000e+00, 6.0000000e+04, 4.8078370e+00, 0.0000000e+00,
        6.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1830000e+03,
        8.7600000e+02, 5.0200000e+02, 3.5600000e+02],
       [3.0000000e+00, 7.0000000e+04, 4.3682637e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.5430000e+03,
        1.6210000e+03, 2.5030000e+03, 2.6190000e+03],
       [4.0000000e+00, 8.0000000e+04, 4.0201092e+00, 0.0000000e+00,
        9.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4800000e+03,
        1.1740000e+03, 6.8800000e+02, 1.9800000e+02]], dtype=float32)>

In [79]:
k = ships_tensor[:,6]
k

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 1., 1.], dtype=float32)>

In [64]:
availability_tensor = tf.zeros(shape=(4))
availability_tensor

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [80]:
inplace_array = np.zeros(4)
inplace_array[available_ships_idx] = 1

In [81]:
inplace_array

array([1., 0., 1., 1.])

In [84]:
indices_array = np.zeros(shape=ships_tensor.shape)
indices_array[:,6] = 1
indices_array


array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [85]:
indices = tf.cast(tf.where(tf.equal(indices_array, 1)), tf.int32)
indices

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 6],
       [1, 6],
       [2, 6],
       [3, 6]], dtype=int32)>

In [86]:
scatter = tf.scatter_nd(indices, inplace_array, shape=tf.shape(indices_array))
scatter

<tf.Tensor: shape=(4, 11), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])>

In [95]:
scatter = tf.cast(scatter, tf.float32)

In [87]:
inverse_mask = tf.cast(tf.math.logical_not(indices_array), tf.float32)
inverse_mask

<tf.Tensor: shape=(4, 11), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]], dtype=float32)>

In [97]:
z = tf.multiply(inverse_mask,ships_tensor)
z

<tf.Tensor: shape=(4, 11), dtype=float32, numpy=
array([[1.0000000e+00, 5.0000000e+04, 5.3851833e+00, 1.2989447e+00,
        1.0000000e+01, 1.0000000e+01, 0.0000000e+00, 8.3000000e+01,
        3.4200000e+02, 1.1400000e+03, 1.2560000e+03],
       [2.0000000e+00, 6.0000000e+04, 4.8078370e+00, 0.0000000e+00,
        6.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.1830000e+03,
        8.7600000e+02, 5.0200000e+02, 3.5600000e+02],
       [3.0000000e+00, 7.0000000e+04, 4.3682637e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5430000e+03,
        1.6210000e+03, 2.5030000e+03, 2.6190000e+03],
       [4.0000000e+00, 8.0000000e+04, 4.0201092e+00, 0.0000000e+00,
        9.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.4800000e+03,
        1.1740000e+03, 6.8800000e+02, 1.9800000e+02]], dtype=float32)>

In [93]:
scatter

<tf.Tensor: shape=(4, 11), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])>

In [96]:
tf.add(scatter,z, tf.cast(scatter,tf.float32))

<tf.Tensor: shape=(4, 11), dtype=float32, numpy=
array([[1.0000000e+00, 5.0000000e+04, 5.3851833e+00, 1.2989447e+00,
        1.0000000e+01, 1.0000000e+01, 1.0000000e+00, 8.3000000e+01,
        3.4200000e+02, 1.1400000e+03, 1.2560000e+03],
       [2.0000000e+00, 6.0000000e+04, 4.8078370e+00, 0.0000000e+00,
        6.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.1830000e+03,
        8.7600000e+02, 5.0200000e+02, 3.5600000e+02],
       [3.0000000e+00, 7.0000000e+04, 4.3682637e+00, 0.0000000e+00,
        2.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.5430000e+03,
        1.6210000e+03, 2.5030000e+03, 2.6190000e+03],
       [4.0000000e+00, 8.0000000e+04, 4.0201092e+00, 0.0000000e+00,
        9.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4800000e+03,
        1.1740000e+03, 6.8800000e+02, 1.9800000e+02]], dtype=float32)>

### Tensorflow Tip

Assign values to a tensor at specific indices

In [ ]:
input_array = np.array([2, 4, 7, 11, 3, 8, 9, 19, 11, 7])
inplace_array = np.array([10, 20])
indices_array = np.array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

# [[2], [6]] 
indices = tf.cast(tf.where(tf.equal(indices_array,1)),tf.int32)
print(indices)

# [0, 0, 10, 0, 0, 0, 20, 0, 0, 0]
scatter = tf.scatter_nd(indices, inplace_array, shape=tf.shape(input_array))
print(scatter)

# [1, 1, 0, 1, 1, 1, 0, 1, 1, 1]
inverse_mask = tf.cast(tf.math.logical_not(indices_array), tf.int32)
print(inverse_mask)

# [2, 4, 0, 11, 3, 8, 0, 19, 11, 7]
input_array_zero_out = tf.multiply(inverse_mask, input_array)
print(input_array_zero_out)

# [2, 4, 10, 11, 3, 8, 20, 19, 11, 7]
output = tf.add(input_array_zero_out, tf.cast(scatter, tf.int32))
print(output)

In [ ]:
# [[2], [6]] 
indices = tf.cast(tf.where(tf.equal(indices_array,1)),tf.int32)
print(indices)

In [ ]:
# [0, 0, 10, 0, 0, 0, 20, 0, 0, 0]
scatter = tf.scatter_nd(indices, inplace_array, shape=tf.shape(input_array))
print(scatter)

In [ ]:
# [1, 1, 0, 1, 1, 1, 0, 1, 1, 1]
inverse_mask = tf.cast(tf.math.logical_not(indices_array), tf.int32)
print(inverse_mask)

In [ ]:
# [2, 4, 0, 11, 3, 8, 0, 19, 11, 7]
input_array_zero_out = tf.multiply(inverse_mask, input_array)
print(input_array_zero_out)

In [ ]:
# [2, 4, 10, 11, 3, 8, 20, 19, 11, 7]
output = tf.add(input_array_zero_out, tf.cast(scatter, tf.int32))
print(output)

In [ ]:
# encoder mlp

# see https://keras.io/examples/structured_data/structured_data_classification_from_scratch/
# see https://www.tensorflow.org/tutorials/generative/autoencoder
# Create an Integer Categorical Feature for contract_type