In [ ]:
# autoreloading modules that i change in vscode
%load_ext autoreload
%autoreload 2

In [1]:
import gym
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from importlib import reload
import sys

In [2]:
# load data
data_dict = {
    "fleet_path": "data/fleet_small.csv",
    "ports_path": "data/ports_10.csv",
    "dm_path": "data/distance_matrix.csv",
}


ports_df = pd.read_csv(data_dict["ports_path"])
fleet_df = pd.read_csv(data_dict["fleet_path"])
distance_matrix = pd.read_csv(data_dict["dm_path"])

In [10]:
from env.env import CarbonEnv
from models.models import BaselineNet, PolicyNet

In [29]:
# run this cell when needing to reload the classes CarbonEnv, BaselineNet, PolicyNet

del sys.modules['models.models']
del sys.modules['env.env']

from env.env import CarbonEnv
from models.models import BaselineNet, PolicyNet

In [30]:
envo = CarbonEnv()

In [36]:
envo.action_space_dim[0]

13

In [32]:
envo.embedding_size

128

In [33]:
initial_state = envo.state

In [34]:
baseline_net = BaselineNet(embedding_size=envo.embedding_size)

In [39]:
policy_net = PolicyNet(embedding_size=envo.embedding_size,output_size=envo.action_space_dim[0])

In [40]:
categorical_distribution = policy_net.action_distribution(initial_state)

KeyError: 'contracts_tensor'

In [41]:
initial_state

{'contracts_state': <tf.Tensor: shape=(4, 10), dtype=float32, numpy=
 array([[7.0000e+00, 1.0000e+00, 4.0000e+00, 0.0000e+00, 5.0000e+00,
         7.8081e+04, 6.0000e+00, 1.0000e+00, 4.9200e+02, 6.0000e+00],
        [2.0000e+00, 1.0000e+00, 4.0000e+00, 0.0000e+00, 1.1000e+01,
         7.6281e+04, 1.2000e+01, 1.0000e+00, 2.2370e+03, 1.4000e+01],
        [9.0000e+00, 5.0000e+00, 3.0000e+00, 0.0000e+00, 8.0000e+00,
         6.4569e+04, 9.0000e+00, 1.0000e+00, 1.4800e+03, 1.1000e+01],
        [2.0000e+00, 9.0000e+00, 3.0000e+00, 0.0000e+00, 1.3000e+01,
         6.6132e+04, 1.4000e+01, 1.0000e+00, 2.7640e+03, 1.3000e+01]],
       dtype=float32)>,
 'ships_state': <tf.Tensor: shape=(4, 11), dtype=float32, numpy=
 array([[1.0000000e+00, 5.0000000e+04, 5.3851833e+00, 0.0000000e+00,
         3.0000000e+00, 0.0000000e+00, 1.0000000e+00, 8.8600000e+02,
         1.6530000e+03, 1.1470000e+03, 1.6530000e+03],
        [2.0000000e+00, 6.0000000e+04, 4.8078370e+00, 0.0000000e+00,
         8.0000000e+00,

In [ ]:
value = baseline_net.forward(initial_state)

In [ ]:
baseline_net = BaselineNet()

In [ ]:
envo.observation_space_dim

In [ ]:
envo.action_space_dim

In [ ]:
envo.action_space["actions"].shape

In [ ]:
envo.observation_space["contracts_state"].shape

In [ ]:
envo.observation_space["ships_state"].shape

In [ ]:
envo.observation_space["contracts_mask"].shape

In [ ]:
envo.observation_space["ships_mask"].shape

In [ ]:
ships = envo.create_contracts_tensor()

In [ ]:
ships[0]

In [ ]:
ships[1][:, 4] - 1

In [ ]:
for i in range(0, 8):

    day = i // 4
    print(day)

In [ ]:
# encoder mlp

# see https://keras.io/examples/structured_data/structured_data_classification_from_scratch/
# see https://www.tensorflow.org/tutorials/generative/autoencoder
# Create an Integer Categorical Feature for contract_type

In [ ]:
# Delay

contracts = create_contrs(seed=56)
agent_speed = 10
agent_ship = 2
ship_current_port = 4
contract = contracts.loc[0]
start_port_number = contract.start_port_number
end_port_number = contract.end_port_number
trip_1_hours = find_distance(ship_current_port,start_port_number) / agent_speed
print(dt_1_hours)
trip_2_hours = find_distance(start_port_number,end_port_number) / agent_speed
print(dt_2_hours)
trip_total_hours = trip_1_hours + trip_2_hours


trip_total_days = round(trip_total_hours / 24)
print(trip_total_days)

contract_duration = contract.contract_duration
delay = trip_total_days - contract_duration
delay_penalty_factor_per_day = 10

reward = 0
penalty = 0 
if delay <= 0:
    # I arrived on time
    # provide a constant reward > 0 
    reward = 10
    # 
else:
    # I arrived late 
    # penalty < 0
    delay_in_days = -delay
    penalty = delay_penalty_factor_per_day * delay_in_days

print(f"The delay is {delay} days")
print(f"The reward is {reward}")
print(f"The penalty is {penalty}")

# cargo_size vs ship_shize

contracts = create_contrs(seed=56)

# gia ka8e contract se spawned contracts

contract = contracts.loc[0]

fleet_df
# elegxw ka8e ploio pou einai available dhladh exei availability 1 
mask_of_available_ships = fleet_df['ship_availability'] == 1

available_ships = fleet_df[mask_of_available_ships]

available_ships_numbers = available_ships.ship_number

available_ships_numbers



# checkare sto masking an kaneis mask out tous assous h ta mhdenika

# gia ka8e tetoio ploio


# get ship_number

ship_numbers = 
agent_ship_selection = 2

# get ship info
ship_mask = fleet_df['ship_number'] == agent_ship_selection

ship_info = fleet_df[ship_mask]
print(ship_info)

ship_current_port = ship_info.current_port
print(ship_current_port)






start_port_number = contract.start_port_number
end_port_number = contract.end_port_number
trip_1_distance = find_distance(ship_current_port,start_port_number)
print(trip_1_distance)
trip_2_distance = find_distance(start_port_number,end_port_number)
print(trip_2_distance)
trip_total_distance = trip_1_distance + trip_2_distance




trip_total_days = round(trip_total_hours / 24)
print(trip_total_days)

contract_duration = contract.contract_duration
delay = trip_total_days - contract_duration
delay_penalty_factor_per_day = 10

reward = 0
penalty = 0 
if delay <= 0:
    # I arrived on time
    # provide a constant reward > 0 
    reward = 10
    # 
else:
    # I arrived late 
    # penalty < 0
    delay_in_days = -delay
    penalty = delay_penalty_factor_per_day * delay_in_days

print(f"The delay is {delay} days")
print(f"The reward is {reward}")
print(f"The penalty is {penalty}")
